### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by mrzhangzizhen123** [saurabheights/DiabeticRetinopathyDetection#5]
Where to put the data path?Can you provide the data path?I have kaggle's data set, and I don't know how to put it in, and I can't pre-process it. Can you give me a hand?thank you

**Comment by saurabheights** [comment]
Dear,
 Please check https://github.com/saurabheights/DiabeticRetinopathyDetection/blob/master/setup.sh#L49. Furthermore, you have to simply run the src/preprocess as follows:-

`python ./src/preprocess.py folder_path_to_train_images False`
`python ./src/preprocess.py folder_path_to_test_images False`

P.S. In future, please read the Readme.md before writing an issue.

**Comment by mrzhangzizhen123** [comment]
Can you provide the specific process?I had the same problem in training
Traceback (most recent call last): File "Desktop/DiabeticRetinopathyDetection-master2/src/train_model.py", line 52, in <module> model = model_params['model'](**model_params['model_kwargs'], default_lr=optimizer_params['lr']) TypeError: __init__() got an unexpected keyword argument 'default_lr'

**Comment by mrzhangzizhen123** [comment]
@saurabheights 2019-05-29 21:49:23,326 - Train samples after rebalancing: 3175
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/user3/.cache/torch/checkpoints/resnet18-5c106cde.pth
Traceback (most recent call last):
  File "/home/user3/anaconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/user3/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/user3/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/user3/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/user3/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/user3/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/user3/anaconda3/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/home/user3/anaconda3/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/user3/anaconda3/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/user3/anaconda3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train_model.py", line 52, in <module>
    model = model_params['model'](**model_params['model_kwargs'], default_lr=optimizer_params['lr'])
  File "/home/user3/DR-Detection/src/DRNet.py", line 32, in __init__
    self.resnet = resnet18(pretrained=pretrained)
  File "/home/user3/anaconda3/lib/python3.6/site-packages/torchvision/models/resnet.py", line 226, in resnet18
    **kwargs)
  File "/home/user3/anaconda3/lib/python3.6/site-packages/torchvision/models/resnet.py", line 213, in _resnet
    progress=progress)
  File "/home/user3/anaconda3/lib/python3.6/site-packages/torch/hub.py", line 433, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/user3/anaconda3/lib/python3.6/site-packages/torch/hub.py", line 349, in _download_url_to_file
    u = urlopen(url)
  File "/home/user3/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/user3/anaconda3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/user3/anaconda3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/user3/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/user3/anaconda3/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/user3/anaconda3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
can you help me？

**Comment by saurabheights** [comment]
Dear,
 https://download.pytorch.org/models/resnet18-5c106cde.pth : This is the path to pretrained resnet model. If you open it on firefox, you should be able to download it and save it to this path /home/user3/.cache/torch/checkpoints/resnet18-5c106cde.pth

The above resolution is just to bypass this error. If torchvision finds this model already downloaded, it will not download it again and thus you wont have the issue of URLError. 

P.S. - The UrlError is  not from the repo from from urllib library. This could be due to your network.
P.P.S. - Please, for a new problem, make a new issue.

**Comment by mrzhangzizhen123** [comment]
thanks to your help.but I don't use the folder-visualization.please can you tell me how to use it?

**Comment by saurabheights** [comment]
> thanks to your help.but I don't use the folder-visualization.please can you tell me how to use it?

Dear, this work was done by my colleague and I am not familiar with its code. For now, I can recommend you to read about saliency maps. This code tests where your model focuses on in the image during inference, using derivative of Loss with respect to pixels. P.S. You dont need this code to train or test. This code should take trained model and an image, theoritically, and compute the saliency maps. I am too  busy as of now, to do a walkthrough of the code, for that my apologies.

Finally, 

> Please, for a new problem, make a new issue.

Please take notice of this.
